apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool2
  name: multitool2
  namespace: netology-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool2
  template:
    metadata:
      labels:
        app: multitool2
    spec:
      containers:
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: network-multitool
      terminationGracePeriodSeconds: 30